### PR TITLE
Latest companies.py

### PR DESCRIPTION
**Pull request by DigiH**
Latest companies.py with many changed/fixed entries and around 400 new ones.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/theengs/decoder/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DigiH** [comment]
Will there be any issues with quotes within the quotes of the names when processing? If these actually ever get called up ;)

```
0x094F: "Limited Liability Company "Mikrotikls"",
…
0x0972: "Closed Joint Stock Company "Zavod Flometr" ("Zavod Flometr" CJSC)",
…
etc.
```

**Comment by koenvervloesem** [comment]
No these won't work, that's invalid Python syntax, the quotes should be escaped as `\"` inside the string.

What's the source of your company IDs? For instance, mine just listed Mikrotikls as "Mikrotikls", yours adds the "Limited Liability Company", which doesn't look very relevant.

**Comment by DigiH** [comment]
> What's the source of your company IDs?

I took the download from the Bluetooth SIG site where I usually only do searches in the web interface. Same as you I suppose, from the comment at the top.

So coming from them it should be the latest up to date info. Not sure when you got yours, but there seems to have been many changes and corrections since then. Would be interesting to watch how regularly these entries are updated.

I especially liked the change from
```
-  0x0165: "Milwaukee Tool (formerly Milwaukee Electric Tools)",
+  0x0165: "Milwaukee Tool (Formally Milwaukee Electric Tools)",
```

when scrolling through the diff ;)

> No these won't work, that's invalid Python syntax, the quotes should be escaped as `\"` inside the string.

That's what I thought, so I mentioned these when they also jumped at me during the diff check.

**Comment by koenvervloesem** [comment]
Well, I've actually been toying with the idea of creating a Python package with these company IDs so it can be shared by various Python BLE libraries instead of everyone duplicating this effort and having to keep their version updated. I've actually built a preliminary version of this package some time ago, but never got around publishing it. Maybe I'll do it soon.

For now, can you escape the quotes in your PR?

**Comment by DigiH** [comment]
> For now, can you escape the quotes in your PR?

Done

**Comment by koenvervloesem** [comment]
Thanks!

**Comment by koenvervloesem** [comment]
FYI: I've migrated the company IDs into a separate package and I intend to keep that synchronized with Nordic Semiconductor's database. See https://github.com/theengs/explorer/pull/6

**Comment by DigiH** [comment]
> FYI: I've migrated the company IDs into a separate package and I intend to keep that synchronized with Nordic Semiconductor's database. See #6

Yes, makes it a lot easier to keep in sync, and while not as up to date it also answered my question on how frequently this list is being modified :)

**Pull request merged**
